services:
  bard:
    image: bard
    build: .
    ports:
      - "4533:4533"
    expose:
      - 4533
    user: 1000:1000
    container_name: bard
    restart: unless-stopped
    environment:
      ND_CONFIGFILE: "/data/navidrome.toml"
    group_add:
      - "29"
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "./navidrome/data:/data"
      - "./music:/music:ro"

