services:
  mopidy:
    build: .
    container_name: bard 
    restart: unless-stopped
    ports:
      - "6680:6680"
      - "6600:6600"
    volumes:
      - ../music:/var/lib/mopidy/media:ro
      - ./data:/var/lib/mopidy/local
      - ./config:/config
    environment:
      - MOPIDY_CONFIG=/config/mopidy.conf
    devices:
      - "/dev/snd:/dev/snd"

